### ISSUE TITLE
Enhance output on publish problem / try reconnect

### ISSUE THREAD

**Issue by mopore** [mopore/jni-home-automate-shared#1]
```
docker logs hue_bridge_control_api | vim -
(node:8) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Connection loss No. 1
connect ECONNREFUSED 192.168.199.119:1883
Trace
    at MqttClient.<anonymous> (/app/dist/shared/mqtt/MqttServerConnection.js:63:29)
    at MqttClient.emit (node:events:406:35)
    at Socket.streamErrorHandler (/app/node_modules/mqtt/lib/client.js:460:12)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
There is no active connection!
Trace
    at MqttServerConnection.checkClientAndConnection (/app/dist/shared/mqtt/MqttServerConnection.js:190:21)
    at MqttServerConnection._publish (/app/dist/shared/mqtt/MqttServerConnection.js:114:14)
    at /app/dist/shared/mqtt/MqttServerConnection.js:105:18
Error publishing: Error: There is no active connection!
Trace
    at /app/dist/shared/mqtt/MqttServerConnection.js:109:21
/app/dist/shared/mqtt/MqttServerConnection.js:110
            throw new Error(errorMessage);
                  ^

Error: Error publishing: Error: There is no active connection!
    at /app/dist/shared/mqtt/MqttServerConnection.js:110:19
```

**Comment by mopore** [comment]
Should be solved with latest changes on shared type MQTT server connection.
